import Product1 from '../assets/product1.png'
import Product2 from '../assets/product2.png'
import Product3 from '../assets/product3.png'
import Product4 from '../assets/product4.png'
import Product5 from '../assets/product5.png'
import Product6 from '../assets/product6.png'
import Product7 from '../assets/product7.png'
import Product8 from '../assets/product8.png'
let Data =[
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
    {
        image:Product1,
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',
        price: 'Rp 3.500.000',
        discount: '-30%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product5,
        title: 'Grifo',
        description: 'Night lamp',
        offprice: 'Rp 1.500.000',         
    },
    {
        image:Product6,
        title: 'Muggo',
        description: 'Small mug',
        offprice: 'Rp 150.000',  
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product2,
        title: 'Leviosa',
        description: 'Stylish cafe chair',
        offprice: 'Rp 2.500.000',      
    },
    {
        image:Product3,
        title: 'Lolito',
        description: 'Luxury big sofa',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',
        discount: '-50%',
        discountbg: 'bg-Badgebg',       
    },
    {
        image:Product8,
        title: 'Potty',
        description: 'Minimalist flower pot',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product4,
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        offprice: 'Rp 500.000', 
        discount: 'New',
        discountbg: 'bg-Badgebg2',         
    },
    {
        image:Product7,
        title: 'Pingky',
        description: 'Cute bed set',
        offprice: 'Rp 7.000.000',
        price: 'Rp 14.000.000',  
        discount: '-50%',
        discountbg: 'bg-Badgebg2',          
    },
]
export default Data
